/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.daycare.gui;
import edu.neu.csye6200.daycare.CsvReader;
import edu.neu.csye6200.daycare.DayCare;
import edu.neu.csye6200.daycare.classroom.ClassCsvReader;
import edu.neu.csye6200.daycare.teacher.Teacher;
import edu.neu.csye6200.daycare.teacher.TeacherCsvReader;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import org.apache.commons.csv.CSVRecord;
/**
 *
 * @author Manasa
 */
public class AddTeacherUI extends javax.swing.JFrame {

    /**
     * Creates new form AddTeacherUI
     */
    public AddTeacherUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        TextFieldTName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        TeaxtFieldTAge = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextFieldTsex = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaTeacherData = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register a new Faculty Member");
        setBackground(new java.awt.Color(51, 204, 255));

        jLabel4.setText("Teacher Name: ");

        TextFieldTName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTNameActionPerformed(evt);
            }
        });

        jLabel5.setText("Age:");

        jButton3.setText("View Alerts");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        TeaxtFieldTAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaxtFieldTAgeActionPerformed(evt);
            }
        });

        jLabel6.setText("Sex: ");

        TextFieldTsex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTsexActionPerformed(evt);
            }
        });

        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TextAreaTeacherData.setColumns(20);
        TextAreaTeacherData.setRows(5);
        jScrollPane2.setViewportView(TextAreaTeacherData);

        jLabel7.setText("Enter Faculty Information");

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFieldTsex, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TeaxtFieldTAge, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldTName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)))
                    .addComponent(jLabel7))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TextFieldTName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TeaxtFieldTAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldTsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldTNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTNameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        TeacherCsvReader tReader = new TeacherCsvReader();
        tReader.getAlerts("Teacher.csv");
        TextAreaTeacherData.setText(tReader.getAlerts("Teacher.csv"));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TeaxtFieldTAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaxtFieldTAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeaxtFieldTAgeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(TextFieldTName.getText().isEmpty() || TeaxtFieldTAge.getText().isEmpty() || TextFieldTsex.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Teacher Name, Age and Gender is Mandatory!", "InfoBox: " + "Success", JOptionPane.INFORMATION_MESSAGE);  

        }else{
        DayCare dc = DayCare.getInstance();
        Teacher obj = new Teacher();

        TeacherCsvReader tCsvReader = new TeacherCsvReader();

        //Fetch latest teacher ID and increment for next ID
        obj.setTeacherId(tCsvReader.getLastestTeacherId()+1);

        //Get input from Textfields - name , age and sex
        String name = TextFieldTName.getText();
        obj.setTname(name);

        String tAge = TeaxtFieldTAge.getText();
        obj.setTage(Integer.parseInt(tAge));

        String sex = TextFieldTsex.getText();
        obj.setTsex(sex);

        //Add the Joining date as current date
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate localDate = LocalDate.now();
        obj.setJoiningDate(localDate.format(dtf));

        // Allocating ClassID
        //Logic will first check if any classroom has 0 teachers and allocate that class to new teacher.
        //If no class has 0 teachers, it will allocate new teacher to the next classroom available in classID order.
        String[] classList = {"A","B","C","D","E","F"};
        boolean breakLoop = false;
        for(String i: classList){

            if(breakLoop == false){
                ClassCsvReader cCsvReader = new ClassCsvReader();
                int tsize = cCsvReader.getClassTeacherSize(i);
                CsvReader reader = new CsvReader();
                CSVRecord info = reader.readFromFile("ClassID",i,"Ratio.csv");
                CsvReader classReader = new CsvReader();
                CSVRecord classInfo = classReader.readFromFile("ClassID",i,"ClassRoom.csv");
                int maxgroupsize = (Integer.parseInt(info.get("MaximumGroupSize")));
                if(Integer.parseInt(classInfo.get("TeacherSize"))==0){
                if(tsize < maxgroupsize){
                    obj.setClassId(i);
                    obj.setAgeGroup(info.get("AgeGroup"));
                    breakLoop = true;
                }
                }
            }
        }
        
        if(obj.getClassId()==null){
                for(String i: classList){

            if(breakLoop == false){
                ClassCsvReader cCsvReader = new ClassCsvReader();
                int tsize = cCsvReader.getClassTeacherSize(i);
                CsvReader reader = new CsvReader();
                CSVRecord info = reader.readFromFile("ClassID",i,"Ratio.csv");
                int maxgroupsize = (Integer.parseInt(info.get("MaximumGroupSize")));
                if(tsize < maxgroupsize){
                    obj.setClassId(i);
                    obj.setAgeGroup(info.get("AgeGroup"));
                    breakLoop = true;
                }               
            }
        }    
        }

        if((obj.getClassId() == null || obj.getClassId().length() == 0)){
            JOptionPane.showMessageDialog(null, "ClassRooms are full! No vacancy currently", "InfoBox: " + "Success", JOptionPane.INFORMATION_MESSAGE);
        }else{

            // Newly allocated teacher
            obj.setStudentSize(0);

            //Update new Teacher record into Teacher.csv file.
            dc.addTeacher(obj);

            // Increment TeacherSize in ClassRoom record for the ClassID new teacher is recruited.
            dc.updateClassTeacher(obj.getClassId());
        }
            JOptionPane.showMessageDialog(null, "Teacher Added", "InfoBox: " + "Success", JOptionPane.INFORMATION_MESSAGE);   }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TextFieldTsexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTsexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTsexActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //clear button
        TextFieldTName.setText("");
        TextFieldTsex.setText("");
        TeaxtFieldTAge.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddTeacherUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TeaxtFieldTAge;
    private javax.swing.JTextArea TextAreaTeacherData;
    private javax.swing.JTextField TextFieldTName;
    private javax.swing.JTextField TextFieldTsex;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
